apiVersion: v1
kind: Pod
metadata:
  name: python-fastapi-oompod
  labels:
    app: python-fastapi-oomapp
spec:
  containers:
  - name: agent-fastapi-oomcontainer
    image: whatap/agent-python-fastapi
    ports:
    - name: fastapi-port
      containerPort: 8000
    env:
    - name: whatap_server_host
      value: "15.165.146.117"
    - name: license
      value: "x41pl22ek7jhv-z43cebasdv4il7-z62p3l35fj5502"
    - name: app_name
      value: "JOB-OOM-TEST"
    - name: app_process_name
      value: "uvicorn"
    - name: whatap.okind
      value: "kaeeyoungkimOOM"
    - name: NODE_IP
      valueFrom: { fieldRef: { fieldPath: status.hostIP } }
    - name: NODE_NAME
      valueFrom: { fieldRef: { fieldPath: spec.nodeName } }
    - name: POD_NAME
      valueFrom: { fieldRef: { fieldPath: metadata.name } }
    resources:
      limits:
        cpu:
          300m
        memory:
          300Mi
  - name: weird-container
    image: nginx
    command: ["whatap-start-agent","restart werid-container"]
  initContainers:
  - name: init-container-1
    image: nginx
    command: ["sh","-c" ,"echo restart Init Container 1"]
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-oom-service
spec:
  selector:
    app: python-fastapi-oomapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: fastapi-port
  type: NodePort
