apiVersion: v1
kind: Pod
metadata:
  name: jykim-test-pod
spec:
  terminationGracePeriodSeconds: 60
  containers:
  - name: jykim-test-container
    image: nginx
    resources:
      requests:
        memory: 50Mi
        cpu: 100m
      limits:
        memory: 100Mi
        cpu: 150m
