apiVersion: v1
kind: PersistentVolume
metadata:
  name: app-volume
  labels:
    type: local
spec:
  storageClassName: app-hostpath-sc
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: app-volume
spec:
  storageClassName: app-hostpath-sc
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Mi
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web-server-pod
  name: web-server-pod
spec:
  containers:
    - image: nginx
      name: web-server-container
      resources: {}
      volumeMounts:
        - name: my-pv
          mountPath: /use/share/nginx/html
  dnsPolicy: ClusterFirst
  restartPolicy: Always
  volumes:
    - name: my-pv
      persistentVolumeClaim:
        claimName: app-volume
status: {}