/*
 *  @(#) YyLex.java
 *  Copyright 2003 the original author or authors. 
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License"); 
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License. 
 *  
 *   This source, generated by JLex(https://www.cs.princeton.edu/~appel/modern/java/JLex/)
 */
package whatap.util.expr;

/*
 *  @(#) YyLex.java
 *  Copyright 2003 the original author or authors. 
 *  
 *  Licensed under the Apache License, Version 2.0 (the "License"); 
 *  you may not use this file except in compliance with the License.
 *  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *  Unless required by applicable law or agreed to in writing, software
 *  distributed under the License is distributed on an "AS IS" BASIS,
 *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *  See the License for the specific language governing permissions and
 *  limitations under the License. 
 *  
 *   This source, generated by JLex(https://www.cs.princeton.edu/~appel/modern/java/JLex/)
 */
 
class YyLex {
	private final int YY_BUFFER_SIZE = 512;
	private final int YY_F = -1;
	private final int YY_NO_STATE = -1;
	private final int YY_NOT_ACCEPT = 0;
	private final int YY_START = 1;
	private final int YY_END = 2;
	private final int YY_NO_ANCHOR = 4;
	private final int YY_BOL = 65536;
	private final int YY_EOF = 65537;

  private int comment_count = 0;
	private java.io.BufferedReader yy_reader;
	private int yy_buffer_index;
	private int yy_buffer_read;
	private int yy_buffer_start;
	private int yy_buffer_end;
	private char yy_buffer[];
	private int yychar;
	private int yyline;
	private boolean yy_at_bol;
	private int yy_lexical_state;

	YyLex (java.io.Reader reader) {
		this ();
		if (null == reader) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(reader);
	}

	YyLex (java.io.InputStream instream) {
		this ();
		if (null == instream) {
			throw (new Error("Error: Bad input stream initializer."));
		}
		yy_reader = new java.io.BufferedReader(new java.io.InputStreamReader(instream));
	}

	private YyLex () {
		yy_buffer = new char[YY_BUFFER_SIZE];
		yy_buffer_read = 0;
		yy_buffer_index = 0;
		yy_buffer_start = 0;
		yy_buffer_end = 0;
		yychar = 0;
		yyline = 0;
		yy_at_bol = true;
		yy_lexical_state = YYINITIAL;
	}

	private boolean yy_eof_done = false;
	private final int YYINITIAL = 0;
	private final int COMMENT = 1;
	private final int yy_state_dtrans[] = {
		0,
		34
	};
	private void yybegin (int state) {
		yy_lexical_state = state;
	}
	private int yy_advance ()
		throws java.io.IOException {
		int next_read;
		int i;
		int j;

		if (yy_buffer_index < yy_buffer_read) {
			return yy_buffer[yy_buffer_index++];
		}

		if (0 != yy_buffer_start) {
			i = yy_buffer_start;
			j = 0;
			while (i < yy_buffer_read) {
				yy_buffer[j] = yy_buffer[i];
				++i;
				++j;
			}
			yy_buffer_end = yy_buffer_end - yy_buffer_start;
			yy_buffer_start = 0;
			yy_buffer_read = j;
			yy_buffer_index = j;
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}

		while (yy_buffer_index >= yy_buffer_read) {
			if (yy_buffer_index >= yy_buffer.length) {
				yy_buffer = yy_double(yy_buffer);
			}
			next_read = yy_reader.read(yy_buffer,
					yy_buffer_read,
					yy_buffer.length - yy_buffer_read);
			if (-1 == next_read) {
				return YY_EOF;
			}
			yy_buffer_read = yy_buffer_read + next_read;
		}
		return yy_buffer[yy_buffer_index++];
	}
	private void yy_move_end () {
		if (yy_buffer_end > yy_buffer_start &&
		    '\n' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
		if (yy_buffer_end > yy_buffer_start &&
		    '\r' == yy_buffer[yy_buffer_end-1])
			yy_buffer_end--;
	}
	private boolean yy_last_was_cr=false;
	private void yy_mark_start () {
		int i;
		for (i = yy_buffer_start; i < yy_buffer_index; ++i) {
			if ('\n' == yy_buffer[i] && !yy_last_was_cr) {
				++yyline;
			}
			if ('\r' == yy_buffer[i]) {
				++yyline;
				yy_last_was_cr=true;
			} else yy_last_was_cr=false;
		}
		yychar = yychar
			+ yy_buffer_index - yy_buffer_start;
		yy_buffer_start = yy_buffer_index;
	}
	private void yy_mark_end () {
		yy_buffer_end = yy_buffer_index;
	}
	private void yy_to_mark () {
		yy_buffer_index = yy_buffer_end;
		yy_at_bol = (yy_buffer_end > yy_buffer_start) &&
		            ('\r' == yy_buffer[yy_buffer_end-1] ||
		             '\n' == yy_buffer[yy_buffer_end-1] ||
		             2028/*LS*/ == yy_buffer[yy_buffer_end-1] ||
		             2029/*PS*/ == yy_buffer[yy_buffer_end-1]);
	}
	private String yytext () {
		return (new String(yy_buffer,
			yy_buffer_start,
			yy_buffer_end - yy_buffer_start));
	}
	private int yylength () {
		return yy_buffer_end - yy_buffer_start;
	}
	private char[] yy_double (char buf[]) {
		int i;
		char newbuf[];
		newbuf = new char[2*buf.length];
		for (i = 0; i < buf.length; ++i) {
			newbuf[i] = buf[i];
		}
		return newbuf;
	}
	private final int YY_E_INTERNAL = 0;
	private final int YY_E_MATCH = 1;
	private String yy_error_string[] = {
		"Error: Internal error.\n",
		"Error: Unmatched input.\n"
	};
	private void yy_error (int code,boolean fatal) {
		System.out.print(yy_error_string[code]);
		System.out.flush();
		if (fatal) {
			throw new Error("Fatal Error.\n");
		}
	}
	private int[][] unpackFromString(int size1, int size2, String st) {
		int colonIndex = -1;
		String lengthString;
		int sequenceLength = 0;
		int sequenceInteger = 0;

		int commaIndex;
		String workString;

		int res[][] = new int[size1][size2];
		for (int i= 0; i < size1; i++) {
			for (int j= 0; j < size2; j++) {
				if (sequenceLength != 0) {
					res[i][j] = sequenceInteger;
					sequenceLength--;
					continue;
				}
				commaIndex = st.indexOf(',');
				workString = (commaIndex==-1) ? st :
					st.substring(0, commaIndex);
				st = st.substring(commaIndex+1);
				colonIndex = workString.indexOf(':');
				if (colonIndex == -1) {
					res[i][j]=Integer.parseInt(workString);
					continue;
				}
				lengthString =
					workString.substring(colonIndex+1);
				sequenceLength=Integer.parseInt(lengthString);
				workString=workString.substring(0,colonIndex);
				sequenceInteger=Integer.parseInt(workString);
				res[i][j] = sequenceInteger;
				sequenceLength--;
			}
		}
		return res;
	}
	private int yy_acpt[] = {
		/* 0 */ YY_NOT_ACCEPT,
		/* 1 */ YY_NO_ANCHOR,
		/* 2 */ YY_NO_ANCHOR,
		/* 3 */ YY_NO_ANCHOR,
		/* 4 */ YY_NO_ANCHOR,
		/* 5 */ YY_NO_ANCHOR,
		/* 6 */ YY_NO_ANCHOR,
		/* 7 */ YY_NO_ANCHOR,
		/* 8 */ YY_NO_ANCHOR,
		/* 9 */ YY_NO_ANCHOR,
		/* 10 */ YY_NO_ANCHOR,
		/* 11 */ YY_NO_ANCHOR,
		/* 12 */ YY_NO_ANCHOR,
		/* 13 */ YY_NO_ANCHOR,
		/* 14 */ YY_NO_ANCHOR,
		/* 15 */ YY_NO_ANCHOR,
		/* 16 */ YY_NO_ANCHOR,
		/* 17 */ YY_NO_ANCHOR,
		/* 18 */ YY_NO_ANCHOR,
		/* 19 */ YY_NO_ANCHOR,
		/* 20 */ YY_NO_ANCHOR,
		/* 21 */ YY_NO_ANCHOR,
		/* 22 */ YY_NO_ANCHOR,
		/* 23 */ YY_NO_ANCHOR,
		/* 24 */ YY_NO_ANCHOR,
		/* 25 */ YY_NO_ANCHOR,
		/* 26 */ YY_NO_ANCHOR,
		/* 27 */ YY_NO_ANCHOR,
		/* 28 */ YY_NO_ANCHOR,
		/* 29 */ YY_NO_ANCHOR,
		/* 30 */ YY_NO_ANCHOR,
		/* 31 */ YY_NO_ANCHOR,
		/* 32 */ YY_NO_ANCHOR,
		/* 33 */ YY_NO_ANCHOR,
		/* 34 */ YY_NO_ANCHOR,
		/* 35 */ YY_NO_ANCHOR,
		/* 36 */ YY_NO_ANCHOR,
		/* 37 */ YY_NO_ANCHOR,
		/* 38 */ YY_NOT_ACCEPT,
		/* 39 */ YY_NO_ANCHOR,
		/* 40 */ YY_NO_ANCHOR,
		/* 41 */ YY_NO_ANCHOR,
		/* 42 */ YY_NO_ANCHOR,
		/* 43 */ YY_NO_ANCHOR,
		/* 44 */ YY_NOT_ACCEPT,
		/* 45 */ YY_NO_ANCHOR,
		/* 46 */ YY_NO_ANCHOR,
		/* 47 */ YY_NO_ANCHOR,
		/* 48 */ YY_NO_ANCHOR,
		/* 49 */ YY_NOT_ACCEPT,
		/* 50 */ YY_NO_ANCHOR,
		/* 51 */ YY_NO_ANCHOR,
		/* 52 */ YY_NO_ANCHOR,
		/* 53 */ YY_NOT_ACCEPT,
		/* 54 */ YY_NO_ANCHOR,
		/* 55 */ YY_NO_ANCHOR,
		/* 56 */ YY_NOT_ACCEPT,
		/* 57 */ YY_NO_ANCHOR,
		/* 58 */ YY_NO_ANCHOR,
		/* 59 */ YY_NOT_ACCEPT,
		/* 60 */ YY_NO_ANCHOR,
		/* 61 */ YY_NOT_ACCEPT,
		/* 62 */ YY_NO_ANCHOR,
		/* 63 */ YY_NOT_ACCEPT,
		/* 64 */ YY_NOT_ACCEPT,
		/* 65 */ YY_NO_ANCHOR,
		/* 66 */ YY_NO_ANCHOR,
		/* 67 */ YY_NO_ANCHOR,
		/* 68 */ YY_NO_ANCHOR,
		/* 69 */ YY_NO_ANCHOR,
		/* 70 */ YY_NO_ANCHOR,
		/* 71 */ YY_NO_ANCHOR,
		/* 72 */ YY_NO_ANCHOR,
		/* 73 */ YY_NO_ANCHOR,
		/* 74 */ YY_NO_ANCHOR,
		/* 75 */ YY_NO_ANCHOR
	};
	private int yy_cmap[] = unpackFromString(1,65538,
"32:8,25:2,26,32:2,25,32:18,25,9,30,32,39,3,14,27,23,24,1,4,28,5,37,2,36:10," +
"22,32,6,8,7,21,32,38:26,32,31,32:2,39,32,15,38:2,17,13,34,38:2,11,38,12,10," +
"38,16,19,38:2,20,35,33,29,38:5,32,18,32:65411,0:2")[0];

	private int yy_rmap[] = unpackFromString(1,76,
"0,1:2,2,1:3,3,4,5,6,1:4,7,1,8,9,1:7,10,1,11,10,12,10:3,13,1:3,14,15,16,17,8" +
",18,19,20,21,22,23,24,25,26,27,12,19,28,29,1,30,31,32,33,34,35,36,37,38,10," +
"39,40,41,42,10,43,44,45")[0];

	private int yy_nxt[][] = unpackFromString(46,40,
"1,2,3,4,5,6,7,8,9,39,10,72:3,45,65,73,72,50,40,72,11,12,13,14,15:2,54,16,72" +
",17,57:2,74,75,72,18,57,72:2,-1:41,19,-1:46,20,-1:39,21,-1:39,22,-1:41,72,6" +
"6,72:2,-1,72:3,-1,72:2,-1:8,72,-1:3,72:3,67,38,72,67,-1:25,15:2,-1:14,17:25" +
",-1:2,17:2,27,41,17:8,-1:36,18,53,-1:12,72:4,-1,72:3,-1,72:2,-1:8,72,-1:3,7" +
"2:3,67,38,72,67,-1:10,28:4,-1,28:3,-1,28:2,-1:8,28,-1:3,28:4,-1,28:2,-1:36," +
"30,-1:3,1,60,62,43:23,35,43:13,-1:10,28:4,-1,28:3,-1,28:2,-1:8,28,-1:3,28:3" +
",-1:2,28:2,-1:8,23,-1:41,72:4,-1,72:3,-1,72,26,-1:8,72,-1:3,72:3,67,38,72,6" +
"7,-1,17:24,47,61,-1,17:2,42,41,17:8,-1,63,64,43:23,-1,43:13,-1,44:25,-1,27," +
"44:2,-1,49,44:8,-1:14,24,-1:35,72:4,-1,72:2,29,-1,72:2,-1:8,72,-1:3,72:3,67" +
",38,72,67,-1,17:24,47,61,-1,17:2,27,41,17:8,-1,48,64,43:23,-1,43:13,-1,44:2" +
"4,56,59,27,44:3,49,44:8,-1:18,25,-1:31,72:3,31,-1,72:3,-1,72:2,-1:8,72,-1:3" +
",72:3,67,38,72,67,-1,63,52,43:23,-1,43:13,-1:10,32,72:3,-1,72:3,-1,72:2,-1:" +
"8,72,-1:3,72:3,67,38,72,67,-1,44:24,56,59,27,44:2,-1,49,44:8,-1:10,72:3,33," +
"-1,72:3,-1,72:2,-1:8,72,-1:3,72:3,67,38,72,67,-1:25,59:2,-1:4,44,-1:9,48,36" +
",43:23,-1,43:13,-1:25,61:2,-1:4,17,-1:9,37,52,43:23,-1,43:13,-1,48,-1,43:23" +
",-1,43:13,-1:2,52,43:23,-1,43:13,-1:10,72:4,-1,72,46,72,-1,72:2,-1:8,72,-1:" +
"3,72:3,67,38,72,67,-1:10,72:2,51,72,-1,72:3,-1,72:2,-1:8,72,-1:3,72:3,67,38" +
",72,67,-1:10,55,72:3,-1,72:3,-1,72:2,-1:8,72,-1:3,72:3,67,38,72,67,-1:10,72" +
":4,-1,72:3,-1,72:2,-1:8,58,-1:3,72:3,67,38,72,67,-1:10,71,72:3,-1,72:3,-1,7" +
"2:2,-1:8,72,-1:3,72:3,67,38,72,67,-1:10,72:4,-1,72:3,-1,72:2,-1:8,72,-1:3,7" +
"2:2,58,67,38,72,67,-1:10,72:4,-1,72:3,-1,72:2,-1:8,68,-1:3,72:3,67,38,72,67" +
",-1:10,72:4,-1,72:3,-1,72,69,-1:8,72,-1:3,72:3,67,38,72,67,-1:10,72:4,-1,70" +
",72:2,-1,72:2,-1:8,72,-1:3,72:3,67,38,72,67");

	public YyToken yylex ()
		throws java.io.IOException, 
Exception

		{
		int yy_lookahead;
		int yy_anchor = YY_NO_ANCHOR;
		int yy_state = yy_state_dtrans[yy_lexical_state];
		int yy_next_state = YY_NO_STATE;
		int yy_last_accept_state = YY_NO_STATE;
		boolean yy_initial = true;
		int yy_this_accept;

		yy_mark_start();
		yy_this_accept = yy_acpt[yy_state];
		if (YY_NOT_ACCEPT != yy_this_accept) {
			yy_last_accept_state = yy_state;
			yy_mark_end();
		}
		while (true) {
			if (yy_initial && yy_at_bol) yy_lookahead = YY_BOL;
			else yy_lookahead = yy_advance();
			yy_next_state = YY_F;
			yy_next_state = yy_nxt[yy_rmap[yy_state]][yy_cmap[yy_lookahead]];
			if (YY_EOF == yy_lookahead && true == yy_initial) {
				return null;
			}
			if (YY_F != yy_next_state) {
				yy_state = yy_next_state;
				yy_initial = false;
				yy_this_accept = yy_acpt[yy_state];
				if (YY_NOT_ACCEPT != yy_this_accept) {
					yy_last_accept_state = yy_state;
					yy_mark_end();
				}
			}
			else {
				if (YY_NO_STATE == yy_last_accept_state) {
					throw (new Error("Lexical Error: Unmatched Input."));
				}
				else {
					yy_anchor = yy_acpt[yy_last_accept_state];
					if (0 != (YY_END & yy_anchor)) {
						yy_move_end();
					}
					yy_to_mark();
					switch (yy_last_accept_state) {
					case 1:
						
					case -2:
						break;
					case 2:
						{ return (new YyToken(0,yytext())); }
					case -3:
						break;
					case 3:
						{ return (new YyToken(1,yytext())); }
					case -4:
						break;
					case 4:
						{ return (new YyToken(2,yytext())); }
					case -5:
						break;
					case 5:
						{ return (new YyToken(10,yytext())); }
					case -6:
						break;
					case 6:
						{ return (new YyToken(11,yytext())); }
					case -7:
						break;
					case 7:
						{ return (new YyToken(20,yytext())); }
					case -8:
						break;
					case 8:
						{ return (new YyToken(21,yytext())); }
					case -9:
						break;
					case 9:
						{	throw new Exception("Illegal character : "+yytext());}
					case -10:
						break;
					case 10:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -11:
						break;
					case 11:
						{ return (new YyToken(42,yytext())); }
					case -12:
						break;
					case 12:
						{ return (new YyToken(43,yytext())); }
					case -13:
						break;
					case 13:
						{ return (new YyToken(50,yytext())); }
					case -14:
						break;
					case 14:
						{ return (new YyToken(51,yytext())); }
					case -15:
						break;
					case 15:
						{ }
					case -16:
						break;
					case 16:
						{ return (new YyToken(1003,yytext())); }
					case -17:
						break;
					case 17:
						{ throw new Exception("Unclosed String : "+yytext()); }
					case -18:
						break;
					case 18:
						{ return (new YyToken(YyToken.DECIMAL, new Long(yytext())));}
					case -19:
						break;
					case 19:
						{ yybegin(COMMENT); comment_count = comment_count + 1; }
					case -20:
						break;
					case 20:
						{ return (new YyToken(22,yytext())); }
					case -21:
						break;
					case 21:
						{ return (new YyToken(23,yytext())); }
					case -22:
						break;
					case 22:
						{ return (new YyToken(30,yytext())); }
					case -23:
						break;
					case 23:
						{ return (new YyToken(31,yytext())); }
					case -24:
						break;
					case 24:
						{ return (new YyToken(40,yytext())); }
					case -25:
						break;
					case 25:
						{ return (new YyToken(41,yytext())); }
					case -26:
						break;
					case 26:
						{ return (new YyToken(41,yytext())); }
					case -27:
						break;
					case 27:
						{	return (new YyToken(YyToken.STRING, yytext().substring(1,yytext().length() - 1))); }
					case -28:
						break;
					case 28:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -29:
						break;
					case 29:
						{ return (new YyToken(40,yytext())); }
					case -30:
						break;
					case 30:
						{ return (new YyToken(YyToken.REAL, new Double(yytext())));}
					case -31:
						break;
					case 31:
						{ return (new YyToken(32,yytext())); }
					case -32:
						break;
					case 32:
						{ return (new YyToken(YyToken.NULL,yytext())); }
					case -33:
						break;
					case 33:
						{ return (new YyToken(YyToken.BOOLEAN, new Boolean(yytext()))); }
					case -34:
						break;
					case 34:
						{ }
					case -35:
						break;
					case 35:
						{ }
					case -36:
						break;
					case 36:
						{ 
	comment_count = comment_count - 1; 
	if(comment_count < 0)
	   throw new Exception("Invalid Comment");
	if (comment_count == 0) {
    		yybegin(YYINITIAL);
	}
}
					case -37:
						break;
					case 37:
						{ comment_count = comment_count + 1; }
					case -38:
						break;
					case 39:
						{	throw new Exception("Illegal character : "+yytext());}
					case -39:
						break;
					case 40:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -40:
						break;
					case 41:
						{ throw new Exception("Unclosed String : "+yytext()); }
					case -41:
						break;
					case 42:
						{	return (new YyToken(YyToken.STRING, yytext().substring(1,yytext().length() - 1))); }
					case -42:
						break;
					case 43:
						{ }
					case -43:
						break;
					case 45:
						{	throw new Exception("Illegal character : "+yytext());}
					case -44:
						break;
					case 46:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -45:
						break;
					case 47:
						{ throw new Exception("Unclosed String : "+yytext()); }
					case -46:
						break;
					case 48:
						{ }
					case -47:
						break;
					case 50:
						{	throw new Exception("Illegal character : "+yytext());}
					case -48:
						break;
					case 51:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -49:
						break;
					case 52:
						{ }
					case -50:
						break;
					case 54:
						{	throw new Exception("Illegal character : "+yytext());}
					case -51:
						break;
					case 55:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -52:
						break;
					case 57:
						{	throw new Exception("Illegal character : "+yytext());}
					case -53:
						break;
					case 58:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -54:
						break;
					case 60:
						{	throw new Exception("Illegal character : "+yytext());}
					case -55:
						break;
					case 62:
						{	throw new Exception("Illegal character : "+yytext());}
					case -56:
						break;
					case 65:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -57:
						break;
					case 66:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -58:
						break;
					case 67:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -59:
						break;
					case 68:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -60:
						break;
					case 69:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -61:
						break;
					case 70:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -62:
						break;
					case 71:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -63:
						break;
					case 72:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -64:
						break;
					case 73:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -65:
						break;
					case 74:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -66:
						break;
					case 75:
						{ return (new YyToken(YyToken.VARIABLE ,yytext()));}
					case -67:
						break;
					default:
						yy_error(YY_E_INTERNAL,false);
					case -1:
					}
					yy_initial = true;
					yy_state = yy_state_dtrans[yy_lexical_state];
					yy_next_state = YY_NO_STATE;
					yy_last_accept_state = YY_NO_STATE;
					yy_mark_start();
					yy_this_accept = yy_acpt[yy_state];
					if (YY_NOT_ACCEPT != yy_this_accept) {
						yy_last_accept_state = yy_state;
						yy_mark_end();
					}
				}
			}
		}
	}
}
