apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: multi-con-pod
  name: multi-con-pod
spec:
  containers:
  - image: nginx
    name: test-con-1
    resources: {}
  - image: busybox
    name: test-con-2
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
